/**
 * events.js — the curated pool "Big Builds" draws episodes from.
 *
 * Same role as pokepod's creatures.js: a hand-vetted list rather than
 * freely-generated history, so facts stay real and tone stays controllable
 * per-event. Add to this list over time; index.js cycles through it without
 * repeats and resets once the pool is exhausted.
 *
 * toneNotes exists because "no doom and gloom" isn't a blanket instruction —
 * each event needs its own steer on what to linger on and what to move past
 * quickly. artPrompt is written to be safe for an image model: no named real
 * people's likenesses, no graphic content, just the scene and the machine.
 */

export const EVENTS = [
  {
    id: 'titanic',
    title: 'The Titanic',
    year: 1912,
    month: 4,
    day: 14,
    location: 'Southampton, England / North Atlantic',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'At 882 feet long, Titanic was the largest moving object ever built by humans at the time',
      'Its hull was divided into 16 watertight compartments, an idea meant to make it "unsinkable"',
      'The disaster led directly to the first International Convention for the Safety of Life at Sea (SOLAS) — the reason every ship today carries enough lifeboats for everyone aboard',
    ],
    toneNotes:
      'Spend most of the episode on the sheer scale and ambition of building Titanic — the size, the engines, the luxury. Mention the sinking briefly and factually without dwelling on people in peril. Land firmly on how this event changed ship safety forever and made every ship built since safer.',
    artPrompt:
      'a grand ocean liner with four smokestacks docked at a busy harbor, seen from a low angle so it looks enormous, warm evening light',
  },
  {
    id: 'hindenburg',
    title: 'The Hindenburg',
    year: 1937,
    month: 5,
    day: 6,
    location: 'Lakehurst, New Jersey, USA',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'The Hindenburg was longer than three football fields end to end',
      'It could cross the Atlantic Ocean in about half the time of an ocean liner',
      'The disaster ended the era of hydrogen airships and led every airship built afterward to use safe, non-flammable helium instead',
    ],
    toneNotes:
      'Focus on the golden age of airships — floating hotels in the sky, the scale, the silence of gliding through clouds. Mention the fire briefly, factually, no injury detail. End on how it changed aircraft safety design forever.',
    artPrompt:
      'a massive silver airship floating serenely above clouds at sunset, art-deco style',
  },
  {
    id: 'golden-gate',
    title: 'The Golden Gate Bridge',
    year: 1937,
    month: 5,
    day: 27,
    location: 'San Francisco, California, USA',
    category: 'build',
    topicType: 'structures',
    engineeringFacts: [
      'Chief engineer Joseph Strauss insisted on a safety net strung under the whole bridge — it saved 19 workers, who nicknamed themselves the "Halfway to Hell Club"',
      'The bridge was painted "International Orange" specifically because it stands out against San Francisco fog',
      'When it opened it was the longest suspension bridge in the world',
    ],
    toneNotes:
      'Pure triumph story. Lean into the safety net as an example of an engineer caring about the people building his design.',
    artPrompt:
      'a bright orange suspension bridge emerging from swirling fog, cables glowing in sunlight',
  },
  {
    id: 'apollo-13',
    title: 'Apollo 13',
    year: 1970,
    month: 4,
    day: 13,
    location: 'Outer space',
    category: 'rescue',
    topicType: 'transportation',
    engineeringFacts: [
      'An oxygen tank exploded 200,000 miles from Earth, and the crew had to power down almost everything to survive',
      'Engineers on the ground built a working CO2 filter fix out of only the materials the astronauts had onboard — including duct tape and a plastic bag',
      'All three astronauts made it home safely; NASA called it a "successful failure"',
    ],
    toneNotes:
      'This is the most purely thrilling problem-solving story in the pool — lean all the way into the ingenuity and teamwork, minimal peril framing, celebratory ending.',
    artPrompt:
      'engineers in a 1970s mission control room full of glowing screens, looking up in relief, warm lighting',
  },
  {
    id: 'brooklyn-bridge',
    title: 'The Brooklyn Bridge',
    year: 1883,
    month: 5,
    day: 24,
    location: 'New York City, USA',
    category: 'build',
    topicType: 'structures',
    engineeringFacts: [
      'It was the first steel-wire suspension bridge ever built',
      'When chief engineer John Roebling died before construction finished, his son Washington took over — and when Washington fell ill, his wife Emily learned the engineering herself and helped lead construction to completion',
      'At the time it opened, it was the longest suspension bridge in the world by far',
    ],
    toneNotes: 'A family-and-teamwork story. Emily Roebling is the heart of this one.',
    artPrompt:
      'a grand stone-towered suspension bridge over a busy 1880s harbor full of sailing ships',
  },
  {
    id: 'panama-canal',
    title: 'The Panama Canal',
    year: 1914,
    month: 8,
    day: 15,
    location: 'Panama',
    category: 'build',
    topicType: 'structures',
    engineeringFacts: [
      'It cuts through 48 miles of jungle and mountain to connect the Atlantic and Pacific Oceans',
      'Its system of locks lifts ships up and over land like a staircase of water',
      'A ship going around South America instead would need to travel about 8,000 extra miles',
    ],
    toneNotes: 'Focus on the water-staircase lock mechanism — kids love how it visibly works.',
    artPrompt:
      'a massive cargo ship rising inside a concrete canal lock, water pouring in, jungle hills in the background',
  },
  {
    id: 'eiffel-tower',
    title: 'The Eiffel Tower',
    year: 1889,
    month: 3,
    day: 31,
    location: 'Paris, France',
    category: 'build',
    topicType: 'buildings',
    engineeringFacts: [
      'It was built for the 1889 World\'s Fair and was only meant to stand for 20 years',
      'Gustave Eiffel calculated its curved shape specifically to resist wind',
      'It is made of over 18,000 individual iron pieces held together by 2.5 million rivets',
    ],
    toneNotes: 'The "meant to be temporary" fact is the hook — build around it.',
    artPrompt: 'an iron lattice tower under construction, cranes and scaffolding, Paris skyline',
  },
  {
    id: 'hoover-dam',
    title: 'The Hoover Dam',
    year: 1935,
    month: 9,
    day: 30,
    location: 'Nevada/Arizona border, USA',
    category: 'build',
    topicType: 'structures',
    engineeringFacts: [
      'It contains enough concrete to pave a two-lane road from San Francisco to New York',
      'Because concrete that thick would take over a century to cool naturally, engineers ran a network of cooling pipes through it — like giant ice cubes inside the dam',
      'It still generates enough electricity to power hundreds of thousands of homes',
    ],
    toneNotes: 'The cooling-pipe trick is a great "clever solution" hook.',
    artPrompt: 'a colossal curved concrete dam holding back a blue reservoir between desert cliffs',
  },
  {
    id: 'empire-state',
    title: 'The Empire State Building',
    year: 1931,
    month: 5,
    day: 1,
    location: 'New York City, USA',
    category: 'build',
    topicType: 'buildings',
    engineeringFacts: [
      'It was built in just 410 days — about the length of a school year and a summer combined',
      'At its fastest, the building rose 4.5 stories every week',
      'It was built during a race to be the world\'s tallest building, and won',
    ],
    toneNotes: 'The speed of construction is the wonder here — make the pace feel astonishing.',
    artPrompt: 'a soaring art-deco skyscraper under construction with steel beams and tiny cranes',
  },
  {
    id: 'transcontinental-railroad',
    title: 'The Transcontinental Railroad',
    year: 1869,
    month: 5,
    day: 10,
    location: 'United States',
    category: 'build',
    topicType: 'transportation',
    engineeringFacts: [
      'Two crews — one working east from California, one working west from Nebraska — raced to meet in the middle',
      'Workers blasted and dug tunnels straight through mountains using hand tools and explosives',
      'When the two tracks finally met in Utah, a golden final spike was driven in',
    ],
    toneNotes: 'The "two crews racing to meet in the middle" structure is a natural, exciting arc.',
    artPrompt: 'a steam locomotive meeting another on a single track through a mountain pass, crowds cheering',
  },
  {
    id: 'channel-tunnel',
    title: 'The Channel Tunnel',
    year: 1994,
    month: 12,
    day: 1,
    location: 'Under the English Channel, between England and France',
    category: 'build',
    topicType: 'structures',
    engineeringFacts: [
      'Giant boring machines dug from both England and France at once, aiming to meet in the exact middle',
      'When the two tunnels finally connected, the two ends were off by only about 14 inches after miles of digging',
      'It runs about 250 feet below the seabed',
    ],
    toneNotes: 'The precision of the "meet in the middle" moment is the wonder — huge machines, tiny margin of error.',
    artPrompt: 'a giant circular tunnel boring machine breaking through rock underground, workers cheering with lights and dust',
  },
  {
    id: 'sydney-opera-house',
    title: 'The Sydney Opera House',
    year: 1973,
    month: 10,
    day: 20,
    location: 'Sydney, Australia',
    category: 'build',
    topicType: 'buildings',
    engineeringFacts: [
      'The building\'s famous curved "shells" were originally impossible to construct until an engineer realized they could all be carved from slices of one giant imaginary sphere',
      'It took 14 years to build — many more than planned — because no one had ever built shapes like this before',
      'It\'s covered in over a million ceramic tiles',
    ],
    toneNotes: 'The "slices of one giant sphere" insight is a great aha-moment beat.',
    artPrompt: 'white shell-shaped roofs on a harbor at sunset, sailboats nearby',
  },
  {
    id: 'tacoma-narrows',
    title: 'Galloping Gertie',
    year: 1940,
    month: 11,
    day: 7,
    location: 'Tacoma, Washington, USA',
    category: 'disaster-with-hope',
    topicType: 'structures',
    engineeringFacts: [
      'The Tacoma Narrows Bridge earned the nickname "Galloping Gertie" because it visibly swayed and rippled in the wind after it opened',
      'It collapsed dramatically in a windstorm — but thanks to warnings that morning, no people were hurt (the only casualty was a dog left in a car)',
      'Studying exactly why it collapsed taught engineers about wind and motion, and every long bridge built since has been designed with that lesson in mind',
    ],
    toneNotes:
      'This is the safest possible disaster story in the pool since no people were harmed — lean into the dramatic, almost funny footage of a bridge bouncing like a wave, then the real lesson it taught engineering.',
    artPrompt: 'a long suspension bridge rippling in a windstorm like a wave, dramatic stormy sky',
  },
  {
    id: 'great-wall',
    title: 'The Great Wall of China',
    year: 700,
    location: 'China',
    category: 'build',
    topicType: 'ancient',
    engineeringFacts: [
      'It was built and rebuilt over more than 2,000 years by many different dynasties, not all at once',
      'Stretched out, its many sections add up to more than 13,000 miles',
      'Builders used whatever materials were nearby — stone in the mountains, packed earth in the plains',
    ],
    toneNotes: 'The "built over 2,000 years, not one project" fact reframes scale in a way kids find delightful.',
    artPrompt: 'an ancient stone wall with watchtowers winding over green mountain ridges into the distance',
  },
  {
    id: 'machu-picchu',
    title: 'Machu Picchu',
    year: 1450,
    location: 'Andes Mountains, Peru',
    category: 'build',
    topicType: 'ancient',
    engineeringFacts: [
      'Inca builders cut stones so precisely that many walls fit together without any mortar at all — not even a piece of paper slides between the blocks',
      'The city sits on a mountain ridge over 7,900 feet high and includes its own water channel system',
      'Its stonework has survived major earthquakes because the stones can shift slightly and settle back into place',
    ],
    toneNotes: 'The mortar-free precision and earthquake resilience are the two wonder-hooks.',
    artPrompt: 'ancient stone terraces and buildings on a green mountain ridge surrounded by misty peaks',
  },
  {
    id: 'pyramids-giza',
    title: 'The Great Pyramid of Giza',
    year: -2560,
    location: 'Giza, Egypt',
    category: 'build',
    topicType: 'ancient',
    engineeringFacts: [
      'It was built from about 2.3 million stone blocks, some weighing as much as a small elephant',
      'For over 3,800 years it was the tallest human-made structure on Earth',
      'Its base is level to within about an inch across its entire massive footprint — without any modern laser tools',
    ],
    toneNotes: 'The precision-without-modern-tools fact is the core wonder.',
    artPrompt: 'a massive stone pyramid under a golden desert sky, workers and ramps visible at its base',
  },
  {
    id: 'wright-flyer',
    title: 'The Wright Flyer',
    year: 1903,
    month: 12,
    day: 17,
    location: 'Kitty Hawk, North Carolina, USA',
    category: 'build',
    topicType: 'transportation',
    engineeringFacts: [
      'Orville and Wilbur Wright ran a bicycle shop and used what they learned about balance and light frames to design their airplane',
      'Their first powered flight lasted only 12 seconds and covered about 120 feet — shorter than a football field',
      'They tested wing shapes using a homemade wind tunnel built in their bicycle shop',
    ],
    toneNotes: 'The bicycle-shop-to-first-flight arc is the whole story — small, careful, patient testing leading to something huge.',
    artPrompt: 'a fragile wood-and-fabric biplane lifting off a sandy dune, two figures running alongside',
  },
  {
    id: 'saturn-v',
    title: 'The Saturn V Rocket',
    year: 1969,
    month: 7,
    day: 16,
    location: 'Cape Kennedy, Florida, USA',
    category: 'build',
    topicType: 'transportation',
    engineeringFacts: [
      'Saturn V remains the most powerful rocket ever successfully flown',
      'It stood taller than a 36-story building',
      'Its five first-stage engines burned about 15 tons of fuel every second at launch',
    ],
    toneNotes: 'Scale and raw power are the wonder here — use big, kid-graspable comparisons.',
    artPrompt: 'a giant white rocket launching with a massive plume of fire and smoke, crowds watching from a distance',
  },
  {
    id: 'burj-khalifa',
    title: 'The Burj Khalifa',
    year: 2010,
    month: 1,
    day: 4,
    location: 'Dubai, United Arab Emirates',
    category: 'build',
    topicType: 'buildings',
    engineeringFacts: [
      'At over half a mile tall, it is the tallest building ever constructed',
      'Its Y-shaped floor plan was specifically designed to reduce wind forces as it gets taller',
      'It has over 160 floors and its own high-speed elevator system to reach them',
    ],
    toneNotes: 'The wind-resistant Y-shape is the clever-solution hook.',
    artPrompt: 'an ultra-tall, tapering glass skyscraper piercing through clouds, city lights below at dusk',
  },
  {
    id: 'mount-rushmore',
    title: 'Mount Rushmore',
    year: 1941,
    month: 10,
    day: 31,
    location: 'Black Hills, South Dakota, USA',
    category: 'build',
    topicType: 'buildings',
    engineeringFacts: [
      'Sculptor Gutzon Borglum and about 400 workers used dynamite to remove most of the rock, then finer tools for detail',
      'Nearly 90% of the mountain was carved away using carefully placed dynamite blasts — precise enough to leave the faces intact',
      'No workers died during the 14 years of carving, an unusual safety record for the era and the explosives involved',
    ],
    toneNotes: 'The precision-with-dynamite contrast is the wonder — huge, controlled power used with careful precision.',
    artPrompt: 'giant carved stone faces on a mountainside, scaffolding and tiny worker figures for scale',
  },

  // --- merged in from events-batch2.js (Aug 15, 2026) ---

  // --- flagship pick: zero casualties, true "own your mistake" story ---
  {
    id: 'citicorp-center',
    title: 'The Citicorp Center Crisis',
    year: 1978,
    month: 7,
    day: 24,
    location: 'New York City, USA',
    category: 'rescue',
    topicType: 'buildings',
    engineeringFacts: [
      'A year after the 59-story tower opened, an engineering student\'s question led the building\'s own structural engineer, William LeMessurier, to re-check his math — and discover the building could topple in a strong enough storm',
      'Rather than stay quiet, LeMessurier reported the flaw himself and organized a fix: welding thick steel plates over 200 joints, working through the night for weeks',
      'Hurricane season was approaching the whole time repairs were underway, and the work finished just before a real hurricane threatened the city — the building has stood safely ever since',
    ],
    toneNotes:
      'This is the best kind of story in the pool: nobody was hurt, and the hero move was an adult admitting a mistake and fixing it fast rather than hiding it. Lean hard into the honesty-and-responsibility angle — this is a great "even experts make mistakes, what matters is what you do next" episode.',
    artPrompt:
      'welders working through the night high up on the steel frame of a skyscraper under construction, city lights below, dramatic and heroic not scary',
  },
  {
    id: 'hartford-civic-center',
    title: 'The Hartford Civic Center Roof',
    year: 1978,
    month: 1,
    day: 18,
    location: 'Connecticut, USA',
    category: 'rescue',
    topicType: 'buildings',
    engineeringFacts: [
      'The arena\'s huge flat roof collapsed under the weight of heavy snow — just a few hours after a full crowd of thousands had gone home',
      'Investigators found the roof\'s space-frame design hadn\'t accounted for how much extra weight could build up in exactly this kind of snowstorm',
      'No one was hurt, and the near-miss led to major changes in how snow-load is calculated for large flat roofs everywhere',
    ],
    toneNotes:
      'A "what a close call, and what we fixed" story with zero injuries — perfect low-stakes tension (empty building, ticking clock of "what if this had happened during the game") followed by pure relief and a real safety lesson.',
    artPrompt:
      'a large arena roof collapsed inward under a blanket of snow at night, empty stadium seats visible below, dramatic but not frightening',
  },
  {
    id: 'kemper-arena',
    title: 'The Kemper Arena Roof',
    year: 1979,
    month: 6,
    day: 4,
    location: 'Kansas City, USA',
    category: 'rescue',
    topicType: 'buildings',
    engineeringFacts: [
      'A storm caused the arena\'s roof to collapse — but it happened at night while the building was completely empty',
      'Investigators traced the failure to a small but critical bolt connection that wasn\'t strong enough for the loads the roof could experience',
      'The roof was rebuilt with a stronger design, and the incident became a standard lesson in how one small connection can matter as much as the big beams around it',
    ],
    toneNotes:
      'Another zero-injury "empty building, small part, big lesson" story — good pacing beat: a storm rolling in, then the reveal that no one was there.',
    artPrompt:
      'a modern arena with a distinctive exposed steel roof structure under a stormy night sky',
  },
  {
    id: 'campanile-san-marco',
    title: "The Bell Tower of Venice",
    year: 1902,
    month: 7,
    day: 14,
    location: 'Venice, Italy',
    category: 'rescue',
    topicType: 'buildings',
    engineeringFacts: [
      "St Mark's Campanile had stood for about 1,000 years before cracks began appearing in its walls",
      'The cracks grew large enough that officials cleared the whole square days before it finally collapsed — the only casualty was a caretaker\'s cat',
      'Venice rebuilt the tower to look exactly as it had before, using the motto "dov\'era, com\'era" — "where it was, how it was"',
    ],
    toneNotes:
      'The gentlest possible disaster story in the whole pool — genuinely funny/charming (a cat!) and a great lesson about paying attention to warning signs. Lean into the "the building was telling everyone for days" detective angle.',
    artPrompt:
      'a tall brick bell tower in a grand Italian piazza with pigeons and evening light, warm and picturesque',
  },

  // --- strong ship picks ---
  {
    id: 'rms-britannic',
    title: "Titanic's Sister Ship",
    year: 1916,
    month: 11,
    day: 21,
    location: 'Aegean Sea',
    category: 'rescue',
    topicType: 'transportation',
    engineeringFacts: [
      'RMS Britannic was built as Titanic\'s sister ship, using everything engineers had just learned from the Titanic disaster — far more lifeboats, a stronger double hull, and higher watertight walls',
      'When Britannic struck a wartime mine and began to sink, those exact improvements meant lifeboats and rescue ships had far more time to reach everyone aboard',
      'The vast majority of everyone on board made it home safely — a direct result of lessons learned just a few years earlier',
    ],
    toneNotes:
      'The single best "here\'s what changed because of Titanic" follow-up episode in the pool. Frame it explicitly as a sequel/answer to the Titanic episode — proof the lessons actually worked.',
    artPrompt:
      'a grand white ocean liner with red crosses painted on its hull, at sea under a bright sky',
  },
  {
    id: 'andrea-doria',
    title: 'The Andrea Doria',
    year: 1956,
    month: 7,
    day: 25,
    location: 'Atlantic Ocean, off Nantucket',
    category: 'rescue',
    topicType: 'transportation',
    engineeringFacts: [
      'Andrea Doria collided with another ocean liner in thick fog and took on water fast',
      'Because her builders had designed her with a double hull and multiple watertight compartments, she stayed afloat for over 11 hours — long enough for nearby ships to rescue nearly everyone aboard',
      'It remains one of the largest successful sea rescues in history',
    ],
    toneNotes:
      'A "the safety design worked exactly as intended" story — most of the drama is in the rescue, not the collision. End on the rescue-ship heroics.',
    artPrompt:
      'an ocean liner listing at an angle in foggy seas at dawn, rescue ships approaching with lights on',
  },
  {
    id: 'costa-concordia',
    title: 'Raising the Costa Concordia',
    year: 2012,
    month: 1,
    day: 13,
    location: 'Isola del Giglio, Italy',
    category: 'rescue',
    topicType: 'transportation',
    engineeringFacts: [
      'The cruise ship Costa Concordia ran aground and rolled onto its side near a small Italian island',
      'Almost everyone aboard made it safely to shore, but the ship itself — as long as three football fields — was left lying on the seafloor',
      'Engineers spent two years building an underwater platform and using giant flotation tanks to slowly roll the entire ship upright again, in one of the largest salvage operations ever attempted',
    ],
    toneNotes:
      'Spend most of the episode on the salvage operation itself, not the grounding — righting a ship that size is a genuinely astonishing engineering feat kids will love the scale of.',
    artPrompt:
      'a massive cruise ship being slowly rotated upright by underwater cables and floating platforms near a rocky coastline',
  },
  {
    id: 'edmund-fitzgerald',
    title: 'The Edmund Fitzgerald',
    year: 1975,
    month: 11,
    day: 10,
    location: 'Lake Superior',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'The Edmund Fitzgerald was one of the largest freighters ever to sail the Great Lakes, hauling iron ore for 17 years',
      'A sudden, ferocious storm with hurricane-force winds and towering waves overwhelmed the ship on Lake Superior',
      'The mystery of exactly what happened in her final minutes has been studied for decades, and the wreck led to real improvements in how Great Lakes freighters are inspected and how storms are tracked',
    ],
    toneNotes:
      'Frame as a mystery and a tribute rather than a tragedy — the famous ballad written about her (mention that a song exists, don\'t quote lyrics) treats her with real reverence. Focus on the scale of the ship and the storm rather than the crew\'s fate.',
    artPrompt:
      'a massive lake freighter battling towering waves under a dark stormy sky',
  },
  {
    id: 'ss-eastland',
    title: 'The Ship That Had Too Many Lifeboats',
    year: 1915,
    month: 7,
    day: 24,
    location: 'Chicago River, USA',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'After the Titanic disaster, ships everywhere were required to carry many more lifeboats — including the SS Eastland',
      'But Eastland was already a bit top-heavy by design, and the extra weight of all those new lifeboats, high up on the deck, made her unstable',
      'While still tied to the dock, loaded with passengers, she rolled onto her side — a hard lesson that a safety fix has to be checked against the whole ship, not just added on top',
    ],
    toneNotes:
      'A genuinely fascinating engineering-irony story — the safety improvement caused the problem. Keep the framing curious and puzzle-like ("how could adding safety equipment make a ship less safe?") rather than dwelling on the outcome.',
    artPrompt:
      'a large early-1900s passenger steamship tied at a river dock, cranes and cityscape in the background',
  },

  // --- strong train picks ---
  {
    id: 'tay-bridge',
    title: 'The Tay Bridge',
    year: 1879,
    month: 12,
    day: 28,
    location: 'Scotland',
    category: 'disaster-with-hope',
    topicType: 'structures',
    engineeringFacts: [
      'The Tay Bridge was, at the time, the longest bridge in the world, built to carry trains high above the Firth of Tay',
      'During a severe storm, high winds caused the central section to collapse just as a train was crossing',
      'Investigators found the original design badly underestimated wind force on the structure — the disaster directly led to formal wind-load calculations becoming standard for every bridge built afterward',
    ],
    toneNotes:
      'Historical distance (140+ years) makes this safe to tell plainly and briefly, then pivot quickly to how every bridge built since owes something to what engineers learned here.',
    artPrompt:
      'a long iron railway bridge stretching across a wide firth under dramatic storm clouds',
  },
  {
    id: 'eschede',
    title: 'The Wheel That Changed Trains Forever',
    year: 1998,
    month: 6,
    day: 3,
    location: 'Germany',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'Germany\'s ICE trains were some of the fastest, smoothest passenger trains ever built, using a special wheel design meant to reduce noise and vibration',
      'A tiny crack — invisible from the outside — slowly grew inside one wheel over months of travel until it finally gave way at high speed',
      'The disaster completely changed how train wheels are designed, tested, and inspected worldwide — ultrasonic scanning to find exactly this kind of hidden crack is now standard',
    ],
    toneNotes:
      'Handle with extra care — heavier event. Spend the bulk of the episode on the "invisible crack" detective angle (how do you find a flaw you can\'t see?) and the technology it led to, keep the incident itself brief and non-graphic.',
    artPrompt:
      'a sleek high-speed train speeding through the German countryside, close-up detail of a train wheel glinting in sunlight',
  },
  {
    id: 'tangiwai',
    title: 'The Mountain That Warned the Train',
    year: 1953,
    month: 12,
    day: 24,
    hemisphere: 'southern',
    location: 'New Zealand',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'A crater lake on the side of an active volcano suddenly burst through its natural dam, sending a wall of mud and water (called a lahar) down toward a rail bridge',
      'The lahar weakened the bridge\'s supports just minutes before a train was due to cross',
      'The disaster led to New Zealand installing permanent monitoring systems on volcanic crater lakes near rail lines — technology that still watches for lahars today',
    ],
    toneNotes:
      'A genuinely thrilling nature-vs-engineering story with a real detective-mystery quality (nobody could see the danger coming). Focus on the volcano/lahar science, which is inherently fascinating to this age group.',
    artPrompt:
      'a steam train crossing a bridge in misty New Zealand mountains with a distant volcano in the background',
  },
  {
    id: 'granville',
    title: 'The Granville Bridge',
    year: 1977,
    month: 1,
    day: 18,
    hemisphere: 'southern',
    location: 'Sydney, Australia',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'A commuter train derailed and struck the supports of a road bridge crossing above the tracks',
      'The impact caused the heavy concrete bridge deck to collapse directly onto the train carriages below',
      'The disaster led to a full overhaul of how bridge supports near rail lines are protected and how track maintenance is inspected across Australia',
    ],
    toneNotes:
      'Keep the mechanism simple and factual, move quickly to the reforms — the lesson here is about protecting bridge supports from exactly this kind of impact.',
    artPrompt:
      'a road bridge over a suburban rail line with morning commuters, Sydney in the background',
  },
  {
    id: 'chatsworth-metrolink',
    title: 'The Signal That Changed American Trains',
    year: 2008,
    month: 9,
    day: 12,
    location: 'California, USA',
    category: 'disaster-with-hope',
    topicType: 'transportation',
    engineeringFacts: [
      'A commuter train missed a red signal and collided head-on with a freight train on the same track',
      'Investigators found the accident could have been automatically prevented if the train had technology to override human error and stop itself',
      'Congress required every major US railroad to install exactly that — Positive Train Control — a system that can now automatically stop a train before this kind of collision happens',
    ],
    toneNotes:
      'A clean "technology fixes a human-factors problem" story — good for explaining how modern trains now have computers watching out for mistakes.',
    artPrompt:
      'a modern commuter train on tracks with a glowing signal light in the foreground, California hills in the background',
  },
  {
    id: 'hightstown',
    title: 'The First Train Wreck Ever Recorded',
    year: 1833,
    month: 11,
    day: 8,
    location: 'New Jersey, USA',
    category: 'build',
    topicType: 'transportation',
    engineeringFacts: [
      'Trains were still brand new technology — this was one of the very first passenger railways in America',
      'An axle on one of the carriages broke, sending that car off the rails',
      'It\'s recognized as the first officially recorded train derailment in history — the very beginning of engineers learning what could go wrong with trains, and starting to design against it',
    ],
    toneNotes:
      'Frame as "the very first time engineers learned this lesson" — genuinely light in tone since it\'s the origin story for train safety inspection generally, not really about a specific tragedy.',
    artPrompt:
      'an early 1830s steam train with small wooden carriages on a countryside track, historical and charming',
  },

  // --- expanded pool, Aug 17, 2026: 24 new disasters (incl. 2 dams) + 23 marvels ---
  {
    id: "empress-of-ireland",
    title: "The Empress of Ireland",
    year: 1914,
    month: 5,
    day: 29,
    location: "St. Lawrence River, Canada",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "The Empress of Ireland collided with another ship in thick fog on the St. Lawrence River and sank in about 14 minutes \u2014 one of the fastest sinkings of a large ocean liner in history",
      "Investigators found watertight doors couldn't be closed fast enough once the hull was breached, which reshaped how quickly future ships were required to seal off flooding compartments",
      "The wreck led directly to stricter fog-signaling and speed rules for ships navigating busy shipping lanes",
    ],
    toneNotes: "Keep the collision and sinking brief and factual \u2014 the speed of the sinking is the point, not a source of suspense to dwell on. Spend most of the episode on how quickly watertight-door and navigation rules changed afterward.",
    artPrompt: "a large ocean liner shrouded in thick river fog at night, another ship's lights barely visible in the mist",
  },
  {
    id: "ss-sultana",
    title: "The Sultana",
    year: 1865,
    month: 4,
    day: 27,
    location: "Mississippi River, near Memphis, USA",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "The Sultana was a steamboat designed to carry a few hundred passengers, but one of her four boilers exploded while she was badly overloaded",
      "Investigators later found the boiler had been hastily patched instead of properly rebuilt just days before",
      "The disaster became one of the clearest early arguments for mandatory, regular steam-boiler inspection \u2014 standard on every steam-powered vessel since",
    ],
    toneNotes: "Frame around the 'hasty patch vs. doing it right' lesson. Historical distance (160+ years) makes this safe to tell plainly and briefly before moving to the inspection-rules lesson.",
    artPrompt: "a large wooden steamboat with twin smokestacks on a wide river at dawn, steam rising",
  },
  {
    id: "herald-of-free-enterprise",
    title: "The Herald of Free Enterprise",
    year: 1987,
    month: 3,
    day: 6,
    location: "Zeebrugge, Belgium",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "The ferry Herald of Free Enterprise left port with its bow doors still open, and water flooded in as soon as it picked up speed",
      "Investigators found no single instrument on the bridge told the crew the doors were open \u2014 a gap in the ship's design, not just a missed checklist item",
      "The disaster led directly to indicator lights being required on every ferry's bridge, and to the modern idea of 'safety culture' \u2014 designing systems so one missed step can't cause a disaster alone",
    ],
    toneNotes: "Focus on the 'no warning light existed' detail \u2014 a genuinely interesting design-gap story, not just human error. End on how ferries everywhere were redesigned afterward.",
    artPrompt: "a car ferry departing a harbor at dusk, bow doors visible, calm sea",
  },
  {
    id: "ss-morro-castle",
    title: "The Morro Castle",
    year: 1934,
    month: 9,
    day: 8,
    location: "Off the coast of New Jersey, USA",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A fire broke out aboard the ocean liner Morro Castle during a storm just off the New Jersey coast, spreading fast through recently updated public spaces finished in flammable materials",
      "The ship's radio operator sent distress calls that helped guide rescue ships to the scene despite the chaos",
      "The disaster led to strict new US maritime rules requiring fire-resistant construction materials and regular fire drills on passenger ships",
    ],
    toneNotes: "The cause is still historically debated \u2014 keep that honest ('investigators never fully agreed on how it started') rather than asserting a single cause. Focus on the material-safety and fire-drill reforms that followed.",
    artPrompt: "a large ocean liner near a rocky coastline with smoke rising, rescue boats approaching, dramatic sky",
  },
  {
    id: "uss-thresher",
    title: "The USS Thresher",
    year: 1963,
    month: 4,
    day: 10,
    location: "North Atlantic Ocean",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "USS Thresher was one of the most advanced submarines ever built, testing how deep a submarine could safely dive",
      "During a deep test dive, a systems failure kept the submarine from surfacing in time",
      "The Navy responded by creating SUBSAFE, an intensely strict quality-control program \u2014 every US submarine built since has passed through it, and no SUBSAFE-certified submarine has ever been lost the same way",
    ],
    toneNotes: "No visible 'incident' to narrate \u2014 the submarine simply didn't return \u2014 so keep it brief and respectful, and spend nearly the entire episode on SUBSAFE, one of the most successful safety programs in engineering history. Good candidate to use sparingly / space far from other heavy episodes.",
    artPrompt: "a submarine silhouette diving into deep blue ocean water",
  },
  {
    id: "mv-estonia",
    title: "The MV Estonia",
    year: 1994,
    month: 9,
    day: 28,
    location: "Baltic Sea",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "The ferry MV Estonia sank in heavy seas after the locks holding its bow visor closed failed under the pounding of large waves",
      "The disaster prompted a complete redesign standard for ferry bow-visor locking systems across Europe",
      "It also led to new international rules requiring ferries to survive flooding of at least two compartments, not just one",
    ],
    toneNotes: "A heavier entry \u2014 keep the mechanism explanation clear and brief, lean hard into the concrete design-standard changes that followed across the whole European ferry industry. Good to space out rather than run near other maritime disaster episodes.",
    artPrompt: "a large car ferry in heavy Baltic Sea swells under a grey stormy sky",
  },
  {
    id: "ashtabula",
    title: "The Ashtabula Bridge Disaster",
    year: 1876,
    month: 12,
    day: 29,
    location: "Ashtabula, Ohio, USA",
    category: "disaster-with-hope",
    topicType: 'structures',
    engineeringFacts: [
      "An iron truss railroad bridge collapsed in a snowstorm just as a train was crossing it, after years of gradual, invisible metal fatigue",
      "Investigators found the bridge's iron design had never been properly load-tested for real winter conditions",
      "The disaster helped launch the practice of independent bridge inspection and rigorous load-testing before any new railroad bridge could open",
    ],
    toneNotes: "Historical distance (150 years) makes this safe to tell plainly. Frame around invisible, slow-building fatigue inside metal \u2014 a genuinely interesting engineering mystery.",
    artPrompt: "an iron truss railway bridge over a snowy ravine at dusk, quiet and wintry",
  },
  {
    id: "old-97",
    title: "The Wreck of the Old 97",
    year: 1903,
    month: 9,
    day: 27,
    location: "Danville, Virginia, USA",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "The Fast Mail train, nicknamed 'Old 97,' was running behind schedule and took a curve on a high trestle far too fast",
      "The wreck became so famous it was turned into one of the best-selling folk songs of the early 20th century, still recorded by musicians today",
      "It became a widely publicized early example of why railroads began enforcing strict speed limits on specific curves and trestles, not just general track speed rules",
    ],
    toneNotes: "Lighter than most in this category \u2014 the folk-song angle is a fun hook kids may recognize a version of. Historical distance makes the crash itself easy to tell briefly and plainly.",
    artPrompt: "a steam locomotive crossing a tall wooden trestle bridge over a river valley, early 1900s",
  },
  {
    id: "clapham-junction",
    title: "The Clapham Junction Rail Crash",
    year: 1988,
    month: 12,
    day: 12,
    location: "London, England",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A commuter train crashed into a stopped train because a signal wrongly showed 'clear' \u2014 the result of old wiring never fully disconnected during recent maintenance",
      "Investigators traced the fault to a single loose wire left from an incomplete rewiring job",
      "The crash led directly to sweeping new UK rules requiring independent double-checking of all safety-critical signal wiring work, not just one technician's sign-off",
    ],
    toneNotes: "A great 'one tiny loose wire' detective story \u2014 keep it focused on the wiring-fault discovery and the double-checking rule it created.",
    artPrompt: "a British commuter train at a signal gantry in grey morning light, London rail lines",
  },
  {
    id: "ladbroke-grove",
    title: "The Ladbroke Grove Rail Crash",
    year: 1999,
    month: 10,
    day: 5,
    location: "London, England",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "Two trains collided head-on after one passed a signal showing danger \u2014 a signal later found notoriously difficult to see clearly in bright sunlight",
      "Investigators found other drivers had passed that same signal in error before, without the warning being acted on in time",
      "The crash accelerated the rollout of automatic train protection technology across the UK \u2014 systems that can now stop a train automatically if a driver misses a danger signal",
    ],
    toneNotes: "Frame around 'a warning sign nobody could quite see' \u2014 an engineering-visibility problem \u2014 and the automatic-stop technology it led to.",
    artPrompt: "a railway signal gantry with red danger lights against a bright sky, tracks converging",
  },
  {
    id: "harrow-wealdstone",
    title: "The Harrow & Wealdstone Rail Crash",
    year: 1952,
    month: 10,
    day: 8,
    location: "London, England",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "In thick fog, a train passed a danger signal and collided with a stopped train, and a third train then crashed into the wreckage moments later",
      "It remains one of the events that most shaped modern railway safety technology in Britain",
      "It accelerated adoption of the Automatic Warning System, which alerts drivers inside the cab itself when a danger signal is ahead, rather than relying on spotting a trackside light in poor visibility",
    ],
    toneNotes: "The fog is the central engineering challenge \u2014 a signal is only useful if a driver can actually see it. Frame around visibility and the in-cab warning technology that followed.",
    artPrompt: "a steam train approaching a signal barely visible through thick fog",
  },
  {
    id: "great-heck",
    title: "The Great Heck Rail Crash",
    year: 2001,
    month: 2,
    day: 28,
    location: "North Yorkshire, England",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A car left the motorway, crossed a barrier, and landed on the railway tracks below just before a train arrived",
      "The collision derailed the passenger train directly into the path of an oncoming freight train",
      "The crash led to a review of roadside barrier design at every UK location where a motorway runs close above a railway line",
    ],
    toneNotes: "An unusual, almost freak-accident cause \u2014 frame it around the barrier-design question it raised rather than dwelling on the collision sequence.",
    artPrompt: "a motorway overpass above a railway line in the English countryside, morning light",
  },
  {
    id: "hither-green",
    title: "The Hither Green Rail Crash",
    year: 1967,
    month: 11,
    day: 5,
    location: "London, England",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A passenger train derailed after running over a broken rail \u2014 a crack that had been growing invisibly inside the metal",
      "Investigators found the type of rail joint in use was especially prone to this kind of hidden fatigue crack",
      "The crash led to widespread adoption of ultrasonic rail-testing equipment, which can 'see' inside a rail to find cracks no inspector could spot by eye",
    ],
    toneNotes: "Pairs nicely with the Eschede story \u2014 another 'invisible crack inside metal' detective story. Keep the derailment brief, spend most of the time on ultrasonic testing as a clever solution.",
    artPrompt: "a rail inspector examining a section of railway track with specialized equipment, close-up detail",
  },
  {
    id: "gare-de-lyon",
    title: "The Gare de Lyon Crash",
    year: 1988,
    month: 6,
    day: 27,
    location: "Paris, France",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A commuter train's brakes failed as it approached a busy Paris terminus, and it collided with a stationary train ahead",
      "Investigators found the braking system had no reliable backup if the primary system failed under certain conditions",
      "The crash led to new requirements for redundant braking systems on commuter trains \u2014 a second, independent way to stop if the first one fails",
    ],
    toneNotes: "Frame around the idea that even brakes need a backup plan \u2014 a clean, simple engineering-redundancy lesson.",
    artPrompt: "a French commuter train arriving at a grand glass-roofed Parisian station",
  },
  {
    id: "congressional-limited",
    title: "The Congressional Limited Derailment",
    year: 1943,
    month: 9,
    day: 6,
    location: "Philadelphia, USA",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A piece of undercarriage equipment on the Congressional Limited came loose at speed and caused the train to derail on a curve at Frankford Junction",
      "That same curve saw a strikingly similar high-speed derailment more than seventy years later, in 2015",
      "Comparing the two crashes became a case study in why a known dangerous curve needs an engineered fix \u2014 like automatic speed control \u2014 not just decades of driver caution",
    ],
    toneNotes: "The 'same curve, 72 years apart' angle is the real hook \u2014 a story about why relying on human caution alone, generation after generation, isn't a real fix. Pairs naturally with Amtrak 188.",
    artPrompt: "a mid-century passenger train rounding a curve through an urban rail junction, 1940s style",
  },
  {
    id: "amtrak-188",
    title: "Amtrak 188",
    year: 2015,
    month: 5,
    day: 12,
    location: "Philadelphia, USA",
    category: "disaster-with-hope",
    topicType: 'transportation',
    engineeringFacts: [
      "A passenger train entered a sharp curve at more than twice the posted speed limit and derailed",
      "The same curve at Frankford Junction had seen a nearly identical derailment in 1943 (see the Congressional Limited)",
      "The crash finally accelerated the nationwide rollout of Positive Train Control \u2014 a system that can automatically slow a train if it's about to take a curve too fast, regardless of the driver",
    ],
    toneNotes: "A more recent entry \u2014 handle with a little extra care and keep it brief and factual. The real story is the technology fix it forced into place nationwide.",
    artPrompt: "a modern passenger train rounding an urban curve, city skyline in the background",
  },
  {
    id: "hyatt-regency",
    title: "The Hyatt Regency Walkway Collapse",
    year: 1981,
    month: 7,
    day: 17,
    location: "Kansas City, USA",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "Two suspended walkways crossing the hotel's atrium collapsed onto a crowded party below",
      "A last-minute change to how the walkways were connected \u2014 swapping one long connecting rod for two shorter ones \u2014 accidentally doubled the load on a single critical connection, without anyone re-checking the math",
      "It became the defining case study taught to nearly every structural engineering student since, about why any design change, however small it seems, needs to be re-verified against the original calculations",
    ],
    toneNotes: "A heavier entry and the definitive lesson in the whole pool about double-checking your work. Keep the collapse itself brief and factual, and spend the bulk of the episode on exactly how a seemingly tiny change in a connection design doubled the load \u2014 that's the genuinely fascinating part.",
    artPrompt: "a grand hotel atrium with elevated walkways crossing high overhead, dramatic architectural lighting",
  },
  {
    id: "ronan-point",
    title: "Ronan Point",
    year: 1968,
    month: 5,
    day: 16,
    location: "London, England",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "A relatively small gas explosion in one apartment caused an entire corner of the high-rise tower to collapse, floor after floor, straight down",
      "Investigators found the building's precast concrete panels weren't designed to hold together if one section failed \u2014 there was no backup structural path",
      "The collapse led to a new principle in building codes worldwide: structural redundancy, meaning a building must be designed so losing one part doesn't bring down the whole thing",
    ],
    toneNotes: "The 'domino effect' visual is dramatic but keep description restrained and factual. Focus on the redundancy principle it created, which now protects virtually every modern high-rise.",
    artPrompt: "a tall 1960s residential tower block against a grey London sky, geometric concrete panels",
  },
  {
    id: "commonwealth-avenue",
    title: "2000 Commonwealth Avenue",
    year: 1971,
    month: 1,
    day: 25,
    location: "Boston, USA",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "An apartment building under construction collapsed floor by floor while concrete was still being poured on an upper level",
      "Investigators found the concrete on lower floors hadn't been given enough time to fully cure and gain its real strength before more weight was added on top",
      "The collapse reshaped construction-sequencing rules \u2014 how long you must wait, and how you must test concrete strength, before loading more weight on top of it",
    ],
    toneNotes: "Frame around the idea that concrete needs real time to become strong \u2014 a patience-and-verification lesson, not just a rush-to-finish story. Pairs naturally with Skyline Towers.",
    artPrompt: "a partially built concrete apartment building with construction cranes, urban Boston skyline",
  },
  {
    id: "iroquois-theatre",
    title: "The Iroquois Theatre Fire",
    year: 1903,
    month: 12,
    day: 30,
    location: "Chicago, USA",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "A fire broke out during a crowded matinee, and many of the theater's exit doors opened inward, jamming shut against the crowd trying to leave",
      "The disaster directly led to the invention of the 'panic bar' \u2014 a horizontal bar across a door that lets anyone open it just by pushing forward, even in a crush of people",
      "That single invention is now required by law on the exit doors of nearly every public building in the world",
    ],
    toneNotes: "Handle gently \u2014 heavier historical event \u2014 but it has one of the strongest 'invention born from tragedy' payoffs in the whole pool. Spend real time on the panic bar itself: how it works and why it changed everything.",
    artPrompt: "an ornate early-1900s theater exterior with grand doors, warm gaslight glow",
  },
  {
    id: "cocoanut-grove",
    title: "The Cocoanut Grove Fire",
    year: 1942,
    month: 11,
    day: 28,
    location: "Boston, USA",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "A fire spread rapidly through a crowded nightclub, and the club's revolving front door \u2014 its main entrance \u2014 jammed as people tried to escape through it",
      "The disaster led directly to modern fire-safety law: exit doors must open outward, must never be locked during business hours, and revolving doors must have regular hinged doors right beside them",
      "Emergency medicine also changed because of it \u2014 doctors treating survivors made major advances in burn and shock treatment still used today",
    ],
    toneNotes: "Handle gently. Focus on the exit-door law it created and, as a genuine bonus, the medical advances that came out of treating survivors \u2014 a real, meaningful silver lining.",
    artPrompt: "a 1940s nightclub exterior at night with a glowing rounded entrance, warm string lights",
  },
  {
    id: "skyline-towers",
    title: "Skyline Towers",
    year: 1973,
    month: 3,
    day: 2,
    location: "Bailey's Crossroads, Virginia, USA",
    category: "disaster-with-hope",
    topicType: 'buildings',
    engineeringFacts: [
      "An apartment building under construction collapsed when workers removed concrete floor supports (shoring) before the concrete above had fully cured",
      "Investigators found the crew was under pressure to move shoring to the next level quickly to keep construction on schedule",
      "The collapse led to strict new rules requiring concrete-strength testing before any supporting shoring can be removed, no matter the schedule pressure",
    ],
    toneNotes: "Similar theme to Commonwealth Avenue \u2014 concrete needs real, tested time. Frame around the schedule-pressure-versus-safety tension and the testing rule it created.",
    artPrompt: "a high-rise apartment building under construction with visible concrete floors and scaffolding",
  },
  {
    id: "st-francis-dam",
    title: "The St. Francis Dam",
    year: 1928,
    month: 3,
    day: 12,
    location: "California, USA",
    category: "disaster-with-hope",
    topicType: 'structures',
    engineeringFacts: [
      "The St. Francis Dam failed catastrophically just hours after its chief engineer personally inspected it and found nothing alarming",
      "Investigators later found the dam had been built on ground that wasn't strong enough to support it \u2014 a geological problem, not a flaw in the concrete itself",
      "The disaster directly created California's dam safety program, the first in the US requiring independent state engineers to review and approve every dam design before construction",
    ],
    toneNotes: "A powerful 'even the expert who inspected it personally missed the real problem' story \u2014 frame around independent review as a genuine safeguard, not a bureaucratic afterthought.",
    artPrompt: "a large concrete dam in a dry California canyon, dramatic cliffs and blue sky",
  },
  {
    id: "south-fork-dam",
    title: "The South Fork Dam",
    year: 1889,
    month: 5,
    day: 31,
    location: "Pennsylvania, USA",
    category: "disaster-with-hope",
    topicType: 'structures',
    engineeringFacts: [
      "The South Fork Dam had been modified over the years in ways that reduced its ability to handle heavy flooding, including lowering its height and blocking spillway pipes",
      "After days of extremely heavy rain, the dam gave way, releasing the lake behind it all at once",
      "The disaster prompted one of the first large-scale organized relief efforts in American history, helping establish the American Red Cross's role in disaster response for generations afterward",
    ],
    toneNotes: "Frame the modifications-over-time angle honestly but briefly, then move to the relief-effort story \u2014 a genuine, inspiring 'humans helping humans' response that followed.",
    artPrompt: "a wide earthen dam holding back a mountain lake, Pennsylvania hills in early summer",
  },
  {
    id: "forth-bridge",
    title: "The Forth Bridge",
    year: 1890,
    month: 3,
    day: 4,
    location: "Scotland",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Forth Bridge is a massive steel cantilever bridge \u2014 instead of hanging from cables like a suspension bridge, its own steel arms balance and support each other outward from three enormous towers",
      "It used more steel than almost any structure built before it, at a scale many engineers of the time doubted was possible",
      "It was built in the wake of the Tay Bridge disaster and was deliberately over-engineered for wind resistance \u2014 it remains standing and in daily use well over a century later",
    ],
    toneNotes: "A great direct sequel to the Tay Bridge story \u2014 this bridge exists because engineers took that earlier lesson seriously. Frame around the cantilever's self-balancing design, a fun physical concept kids can act out with their own arms.",
    artPrompt: "a massive red steel cantilever bridge over a wide firth, dramatic engineering silhouette against sky",
  },
  {
    id: "millau-viaduct",
    title: "The Millau Viaduct",
    year: 2004,
    month: 12,
    day: 14,
    location: "France",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Millau Viaduct's tallest support tower rises taller than the Eiffel Tower, carrying a highway across a deep river valley",
      "Engineers designed impossibly slender-looking towers and cables specifically so the bridge would seem to almost float above the valley's morning fog",
      "It was assembled with extraordinary precision, sliding enormous steel deck sections out from both ends of the valley until they met perfectly in the middle",
    ],
    toneNotes: "Lean into the 'taller than the Eiffel Tower, but built to look delicate' contrast \u2014 strength that doesn't look heavy is the wonder here.",
    artPrompt: "an incredibly tall, slender cable-stayed bridge crossing a deep green valley, morning fog below the deck",
  },
  {
    id: "akashi-kaikyo",
    title: "The Akashi Kaikyo Bridge",
    year: 1998,
    month: 4,
    day: 5,
    location: "Japan",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Akashi Kaikyo Bridge crosses a strait known for powerful currents, heavy ship traffic, and major earthquakes \u2014 engineers had to design for all three at once",
      "During construction, a major earthquake actually shifted the two support towers slightly farther apart \u2014 engineers simply adjusted the bridge's final length to match",
      "It held the record for the longest suspension bridge span in the world for over two decades",
    ],
    toneNotes: "The mid-construction earthquake adjustment is a fantastic 'the ground itself moved and they just adapted' detail \u2014 lean into it.",
    artPrompt: "an enormous suspension bridge spanning a wide strait with ships passing below, blue sky",
  },
  {
    id: "gotthard-tunnel",
    title: "The Gotthard Base Tunnel",
    year: 2010,
    month: 10,
    day: 15,
    location: "Switzerland",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "Two giant tunnel-boring machines started at opposite ends of the Swiss Alps and dug toward each other for years, aiming to meet in the exact middle deep underground",
      "When the two tunnels finally connected, deep beneath the mountains, the alignment was off by only a few centimeters after miles and miles of digging",
      "It became the longest railway tunnel in the world, letting trains pass completely beneath the Alps instead of climbing over them",
    ],
    toneNotes: "A close cousin to the Channel Tunnel story \u2014 the 'meet in the middle' precision is the wonder. Good pairing episode if that one's already aired.",
    artPrompt: "a massive tunnel boring machine breaking through rock deep underground, engineers with lights and hard hats",
  },
  {
    id: "holland-tunnel",
    title: "The Holland Tunnel",
    year: 1927,
    month: 11,
    day: 13,
    location: "New York and New Jersey, USA",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Holland Tunnel was one of the first tunnels built for cars to pass underwater, and engineers faced a problem nobody had really solved before: how do you clear car exhaust out of a tube running beneath a river?",
      "Chief engineer Clifford Holland designed a massive ventilation system with giant fans that completely changes the air inside the tunnel every 90 seconds",
      "The ventilation solution became the standard model for underwater and underground vehicle tunnels built around the world ever since",
    ],
    toneNotes: "Frame around the 'invisible problem nobody else had to solve yet' \u2014 clearing exhaust fumes underwater. The giant-fan solution is very concrete and kid-graspable.",
    artPrompt: "the entrance to a tiled underwater tunnel with early automobiles, 1920s New York waterfront",
  },
  {
    id: "erie-canal",
    title: "The Erie Canal",
    year: 1825,
    month: 10,
    day: 26,
    location: "New York, USA",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "Workers dug 363 miles of canal by hand and with horse-drawn scrapers, connecting the Hudson River all the way to the Great Lakes, before any powered earthmoving equipment existed",
      "Engineers had to invent a stair-step system of locks to lift and lower boats up and down more than 500 feet of elevation change along the route",
      "When it opened, a relay of cannon fire was used to send the news from Buffalo to New York City in about 90 minutes \u2014 an 1825 version of instant messaging",
    ],
    toneNotes: "The cannon-relay detail is a delightful, very concrete hook kids will love \u2014 an old-fashioned 'instant message' across hundreds of miles.",
    artPrompt: "a horse-drawn canal boat passing through a stone lock, tree-lined banks, early 1800s",
  },
  {
    id: "three-gorges-dam",
    title: "The Three Gorges Dam",
    year: 2012,
    month: 7,
    day: 4,
    location: "China",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Three Gorges Dam is one of the largest engineering structures ever built, holding back one of the world's biggest rivers",
      "Its hydroelectric generators produce enough electricity to power tens of millions of homes without burning any fuel",
      "Building it required moving over a million people to new homes and rethinking flood control for hundreds of miles downriver \u2014 a reminder that huge engineering projects change more than just the landscape",
    ],
    toneNotes: "Flagged as having real tradeoffs (environmental and human) \u2014 it's fine to mention the scale of resettlement honestly and briefly as part of what 'huge' really means, without turning it into the focus. Keep the tone factual and balanced rather than purely celebratory.",
    artPrompt: "an enormous concrete dam spanning a wide river gorge, hydroelectric intakes visible, misty mountains",
  },
  {
    id: "roman-aqueducts",
    title: "The Roman Aqueducts",
    year: -312,
    location: "Across the Roman Empire",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "Roman engineers moved water across dozens of miles using nothing but gravity \u2014 calculating an extremely gentle, precise downward slope over the entire distance so water would flow on its own",
      "Where a valley was in the way, they built towering stone arches to carry the water channel across at exactly the right height",
      "Some Roman aqueducts carried clean water into cities for well over a thousand years, and a few sections are still standing today",
    ],
    toneNotes: "No modern machines at all \u2014 the wonder is pure math and patience. Great contrast episode to pair with something high-tech like the James Webb telescope.",
    artPrompt: "ancient stone aqueduct arches stretching across a sunlit valley, Mediterranean countryside",
  },
  {
    id: "pont-du-gard",
    title: "The Pont du Gard",
    year: 50,
    location: "France",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Pont du Gard is a three-tiered stone bridge built to carry a Roman aqueduct across a river valley, using precisely cut stone blocks with no mortar holding most of them together",
      "The whole structure drops only about an inch in height across its entire length \u2014 an almost unbelievably gentle, exact slope for water flowing entirely by gravity",
      "It has stood for roughly 2,000 years and is still one of the best-preserved Roman structures in the world",
    ],
    toneNotes: "The 'drops only about an inch across its whole length' fact is a genuinely astonishing, concrete number kids can sit with.",
    artPrompt: "a magnificent three-tiered ancient stone bridge over a turquoise river, golden French countryside",
  },
  {
    id: "thames-barrier",
    title: "The Thames Barrier",
    year: 1984,
    month: 5,
    day: 8,
    location: "London, England",
    category: "build",
    topicType: 'structures',
    engineeringFacts: [
      "The Thames Barrier is a row of giant curved steel gates lying flat on the riverbed, which can rotate upright in minutes to block London's river from a dangerous storm surge",
      "Its shape was inspired by looking at everyday gas taps \u2014 engineers realized a simple rotating valve shape could be scaled up to hold back an entire river",
      "It has been raised to protect London from flooding well over 100 times since it opened, each time closing before the danger arrived, not after",
    ],
    toneNotes: "The 'inspired by a gas tap' origin story is a wonderful example of everyday-object inspiration leading to a massive solution. Frame around planning for a disaster before it happens, not reacting after.",
    artPrompt: "massive curved silver gates rising from a wide river, iconic modern engineering against a cloudy London sky",
  },
  {
    id: "dc-3",
    title: "The Douglas DC-3",
    year: 1935,
    month: 12,
    day: 17,
    location: "USA",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "The DC-3 made its first flight on December 17, 1935 \u2014 exactly 32 years to the day after the Wright Brothers' first powered flight",
      "It wasn't the fastest or most advanced plane of its time, but it was reliable enough that airlines could finally make regular passenger flights that didn't depend on perfect conditions",
      "Thousands of DC-3s were built, and some are still flying cargo and passengers in remote parts of the world today, nearly a century later",
    ],
    toneNotes: "The Wright-Flyer-anniversary coincidence is a great connecting detail if that episode has already aired. Frame around 'reliable, not flashy' as its own kind of engineering achievement.",
    artPrompt: "a classic silver twin-propeller airplane on a sunlit 1930s airfield runway",
  },
  {
    id: "boeing-747",
    title: "The Boeing 747",
    year: 1969,
    month: 2,
    day: 9,
    location: "USA",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "When it first flew, the Boeing 747 was so much larger than any earlier passenger plane that engineers had to invent new hangars, runways, and airport gates just to handle it",
      "Its distinctive hump shape came from a practical decision \u2014 the cockpit was raised above the main cabin so the nose could open upward for loading huge cargo",
      "It became known as the 'Queen of the Skies' and helped make long-distance international travel affordable for ordinary families for the first time",
    ],
    toneNotes: "The hump's practical cargo-door origin is a fun 'form follows function' detail. Frame around the idea that a truly big leap sometimes requires rebuilding everything around it, not just the machine itself.",
    artPrompt: "a massive four-engine jumbo jet with its distinctive upper-deck hump, taking off into a bright sky",
  },
  {
    id: "apollo-guidance-computer",
    title: "The Apollo Guidance Computer",
    year: 1966,
    location: "Apollo spacecraft",
    category: "build",
    topicType: 'inventions',
    engineeringFacts: [
      "The computer that helped guide astronauts to the Moon had far less computing power than a modern calculator watch",
      "Engineers had to write every instruction with extreme care, since there was no room to waste a single bit of memory",
      "It pioneered integrated circuits at a scale nobody had attempted before, directly helping kick-start the modern computer chip industry",
    ],
    toneNotes: "No single fixed date \u2014 this is about a technology across the whole Apollo program. Frame around 'less power than the tiniest device you own today' as a jaw-dropping, very concrete comparison.",
    artPrompt: "an astronaut's gloved hands operating a compact 1960s spacecraft control panel with small buttons and switches",
  },
  {
    id: "apollo-11",
    title: "Apollo 11",
    year: 1969,
    month: 7,
    day: 20,
    location: "The Moon",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "Landing on the Moon required solving problems in propulsion, navigation, life support, and communications all at once, with hundreds of thousands of people working on different pieces of the puzzle",
      "The lunar module's onboard computer flashed unexpected alarm codes during the actual landing, and a ground engineer had to instantly recognize them as safe to ignore so the landing could continue",
      "It remains one of the most precisely coordinated achievements by any group of people in history \u2014 thousands of separate jobs all had to go right, in order, without a single do-over",
    ],
    toneNotes: "The best 'team achievement' episode in the whole pool \u2014 no single hero, thousands of correct decisions. The alarm-code moment is a great real-time-problem-solving beat.",
    artPrompt: "an astronaut descending a ladder onto a grey lunar surface, Earth visible in the black sky above",
  },
  {
    id: "space-shuttle",
    title: "The Space Shuttle",
    year: 1981,
    month: 4,
    day: 12,
    location: "Cape Canaveral, USA",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "Before the Space Shuttle, every rocket that launched astronauts into space was used exactly once and then discarded",
      "Engineers had to solve an entirely new problem: how do you build something that can survive launching into space, working in orbit, and then coming back through the fiery heat of re-entry \u2014 and do it again and again?",
      "The first Space Shuttle, Columbia, flew on April 12, 1981 \u2014 exactly 20 years to the day after the first human ever reached space",
    ],
    toneNotes: "Frame around the 'build it to come back and fly again' reuse challenge as a genuinely different kind of engineering problem than a one-time rocket.",
    artPrompt: "a white space shuttle orbiter launching with two solid rocket boosters, brilliant exhaust plume",
  },
  {
    id: "hubble-telescope",
    title: "The Hubble Space Telescope",
    year: 1990,
    month: 4,
    day: 24,
    location: "Earth orbit",
    category: "rescue",
    topicType: 'transportation',
    engineeringFacts: [
      "Shortly after launch, engineers discovered Hubble's massive mirror had been ground very slightly the wrong shape, blurring its images",
      "Because engineers had deliberately designed Hubble so astronauts could visit and service it in orbit, a repair mission was possible \u2014 something no earlier space telescope had ever allowed for",
      "Astronauts installed corrective optics during a dramatic spacewalk mission, and Hubble went on to capture some of the most important images in the history of astronomy",
    ],
    toneNotes: "A genuine 'mistake fixed, not hidden' story \u2014 one of the best in the whole pool for the idea that good engineering plans for its own mistakes. Spend real time on the repair mission itself, not just the flaw.",
    artPrompt: "a spacewalking astronaut working on a large telescope in orbit, Earth glowing below",
  },
  {
    id: "iss",
    title: "The International Space Station",
    year: 1998,
    month: 11,
    day: 20,
    location: "Low Earth orbit",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "The International Space Station was assembled piece by piece in orbit, launched on more than 40 separate rockets from multiple countries over more than a decade",
      "Astronauts used robotic arms and spacewalks to connect modules together hundreds of miles above Earth, where a single dropped tool could float away forever",
      "People from more than a dozen countries have worked together continuously aboard it since 2000 \u2014 one of the longest continuous human presences anywhere off Earth",
    ],
    toneNotes: "Frame around 'a house built one piece at a time, in orbit, by people from different countries who had never met in person' \u2014 cooperation itself is the engineering marvel here.",
    artPrompt: "a large modular space station with solar panels against the curve of Earth, sunlight glinting",
  },
  {
    id: "james-webb",
    title: "The James Webb Space Telescope",
    year: 2021,
    month: 12,
    day: 25,
    location: "Deep space",
    category: "build",
    topicType: 'transportation',
    engineeringFacts: [
      "Webb's mirror and sunshield were far too large to fit inside any rocket while fully assembled, so engineers designed the entire telescope to fold up like origami for launch",
      "After launch, it had to unfold itself automatically in space through more than 300 separate steps, any one of which could have failed with no way for anyone to fix it by hand",
      "Every single one of those steps worked correctly on the first try, and Webb is now the most powerful space telescope ever built",
    ],
    toneNotes: "The '300 steps, zero do-overs, no astronaut could reach it to fix a mistake' framing is genuinely nail-biting in a good way \u2014 precision as its own kind of courage.",
    artPrompt: "a golden hexagonal-mirrored space telescope with a large silver sunshield, deep space and stars behind it",
  },
  {
    id: "jacquard-loom",
    title: "The Jacquard Loom",
    year: 1804,
    location: "France",
    category: "build",
    topicType: 'inventions',
    engineeringFacts: [
      "The Jacquard loom used a chain of punched cards to automatically control which threads a weaving machine picked up, letting it weave complex patterns without a person guiding every thread by hand",
      "Each hole (or absence of a hole) on a card was essentially an instruction the machine could 'read' \u2014 an early ancestor of how computers store and follow instructions",
      "Punched-card technology inspired by the Jacquard loom was later used in early computers, more than a century afterward",
    ],
    toneNotes: "No single fixed date. Frame around the idea that a hole punched in a card is basically an instruction \u2014 a very concrete bridge from weaving to computers that kids can genuinely follow.",
    artPrompt: "an ornate wooden weaving loom with a chain of punched cards feeding through it, intricate fabric pattern emerging",
  },
  {
    id: "bessemer-steel",
    title: "The Bessemer Steel Process",
    year: 1856,
    month: 8,
    day: 24,
    location: "England",
    category: "build",
    topicType: 'inventions',
    engineeringFacts: [
      "Before Henry Bessemer's process, making high-quality steel was slow and expensive, so most bridges, rails, and buildings were built from weaker iron instead",
      "Bessemer discovered that blasting air through molten iron burned out its impurities in minutes, transforming it into strong steel \u2014 a process that used to take days",
      "This single discovery made steel cheap enough to build skyscrapers, long bridges, and railroads at a scale that simply wasn't affordable before",
    ],
    toneNotes: "Frame around 'the material had to get better before the buildings could get bigger' \u2014 a great connector episode if paired with things like the Empire State Building or Forth Bridge.",
    artPrompt: "a dramatic 1850s steel foundry with molten metal and sparks, air blasting through a converter vessel",
  },
  {
    id: "assembly-line",
    title: "The Moving Assembly Line",
    year: 1913,
    month: 12,
    day: 1,
    location: "Highland Park, Michigan, USA",
    category: "build",
    topicType: 'inventions',
    engineeringFacts: [
      "Instead of a team of workers building one whole car from start to finish, Henry Ford's factory moved each car past workers on a conveyor system, and each worker did just one specific task as it passed by",
      "This reorganization cut the time it took to build a car from over 12 hours down to about 90 minutes",
      "The idea wasn't a new machine at all \u2014 it was a new way for people and machines to work together, and it reshaped how nearly everything gets manufactured today",
    ],
    toneNotes: "Frame around 'sometimes the invention isn't a machine, it's a better way of working' \u2014 a genuinely different kind of engineering idea than the other marvels.",
    artPrompt: "an early 1900s factory floor with a car chassis moving along a conveyor line, workers at stations",
  },
  {
    id: "container-shipping",
    title: "The Shipping Container",
    year: 1956,
    month: 4,
    day: 26,
    location: "Newark to Houston, USA",
    category: "build",
    topicType: 'inventions',
    engineeringFacts: [
      "Before shipping containers, cargo was loaded onto ships piece by piece by hand \u2014 a slow, expensive process called 'break bulk' shipping",
      "A truck driver named Malcolm McLean had the idea to build one standard-sized steel box that could move straight from a truck to a train to a ship without ever being unpacked and repacked",
      "The first container ship sailed from New Jersey to Texas in 1956, and standardized containers went on to cut global shipping costs so dramatically that they helped reshape the entire world economy",
    ],
    toneNotes: "Frame around 'a truck driver's simple idea' as the invention, not a giant engineering team \u2014 a nice contrast to the space and bridge stories. The standardization angle (same size box, everywhere, forever) is the real insight.",
    artPrompt: "a cargo ship stacked high with colorful steel shipping containers, cranes loading more at a busy port",
  },
  {
    id: "elevator-safety",
    title: "The Elevator Safety Brake",
    year: 1854,
    location: "New York, USA",
    category: "rescue",
    topicType: 'inventions',
    engineeringFacts: [
      "Before Elisha Otis's invention, elevators were considered too dangerous for people to ride, since a snapped lifting cable meant a straight fall",
      "Otis designed a safety brake that automatically grips the elevator's guide rails the instant the cable's tension is lost \u2014 the platform simply can't fall",
      "He famously demonstrated it in public by riding an elevator platform himself and having an assistant cut the cable with an axe \u2014 the platform dropped only a few inches before the brake caught it",
    ],
    toneNotes: "No single confirmed exact date, but the public cable-cutting demonstration is a fantastic, dramatic, kid-friendly hook. Frame around 'the invention that made skyscrapers possible' since tall buildings are pointless if no one trusts the elevator.",
    artPrompt: "a Victorian-era public demonstration with a man standing on an elevator platform, onlookers watching in suspense",
  },
];
